version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3010:3010"
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend
    ports:
      - "3011:3011"
    volumes:
      - ./backend:/app
    depends_on:
      redis:
        condition: service_healthy
      database:
        condition: service_healthy
      elasticity:
        condition: service_healthy
    environment:
      - REDIS_URL=redis://redis:6379
      - CACHE_TTL=600
      - DATABASE_URL=postgresql://postgres:postgres@database:5432/postgres
      - ELASTICSEARCH_NODE=http://elasticity:9200
    networks:
      - app-network

  redis:
    image: redis:7.4-alpine
    ports:
      - "6389:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - redis_data:/data
    networks:
      - app-network

  database:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5442:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  elasticity:
    image: elasticsearch:8.15.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9211:9200"
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail http://localhost:9200/_cluster/health || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 60s
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - app-network

  kibana:
    image: kibana:8.15.0
    ports:
      - "5611:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticity:9200
    depends_on:
      elasticity:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail http://localhost:5601/api/status || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 60s
    networks:
      - app-network
      
  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
    networks:
      - app-network

  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - app-network
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"    
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest      
    networks:
      - app-network
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - backend
    networks:
      - app-network
volumes:
  postgres_data:
  redis_data:
  es_data:

networks:
  app-network:
    driver: bridge
